### PR TITLE
Bug Fixes #16, #17

### LINKED ISSUE #16: Fix Topping Limit Notification
If you submit a pizza with HALF, ALL, ALL, HALF it correctly removes the second ALL and saves HALF, ALL, HALF, but it doesn't give you the limit notification about the removed extra topping. This example is for limit of 2 toppings besides cheese.

### PR DESCRIPTION
**Pull request by Stormsurfer36**
Add fixes to ensure topping limit works.
Cleanup code for topping addition/put it in the pizza.java class
Add clearfix/adjust grid for medium viewport.

### CODE REVIEW

File: src/main/java/com/doeiqts/pizzavoter/domain/Pizza.java [hunk 1]
```diff
@@ -33,7 +34,7 @@ public Pizza(Size size, Crust crust, Sauce sauce) {
         toppingCount = 1.0;
     }
 
-    public Position addTopping(Topping topping, Position position) {
+    public Position addTopping(Topping topping, Position position, HttpServletRequest request) {
```
Comment (doeiqts) [inline src/main/java/com/doeiqts/pizzavoter/domain/Pizza.java]: Ugh, mixing front end and object stuff. Gross. Assuming this is functional, I'll probably change it later.

Comment (Stormsurfer36) [inline src/main/java/com/doeiqts/pizzavoter/domain/Pizza.java]: You can't always get what you want, but yeah I don't like it either. Just was the best way to handle this quickly. That or we make a service class.
